# Generated by Django 6.0.3 on 2026-04-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(
                choices=[('hr_admin', 'Эйчар админ'), ('employee', 'Сотрудник')], max_length=20, verbose_name='Роль'
            ),
        ),
    ]
