# Generated by Django 6.0.4 on 2026-06-09 08:47

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthdayNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True, verbose_name='Включить уведомления')),
                ('days_before', models.PositiveIntegerField(default=1, verbose_name='За сколько дней уведомлять')),
                (
                    'recipients',
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.EmailField(max_length=254),
                        blank=True,
                        default=list,
                        verbose_name='Список Email получателей',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Настройки уведомлений о ДР',
                'verbose_name_plural': 'Настройки уведомлений о ДР',
            },
        ),
        migrations.CreateModel(
            name='BirthdayLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Год поздравления')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'employee',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='birthday_logs',
                        to='employees.employee',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Лог отправки поздравлений',
                'verbose_name_plural': 'Логи отправки поздравлений',
                'unique_together': {('employee', 'year')},
            },
        ),
    ]
