---
services:
  postgres:
    image: "postgres:17-alpine"
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - postgres-net
    env_file: .env
    healthcheck:
      test: pg_isready
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 5s

  redis:
    image: "redis:7-alpine"
    restart: unless-stopped
    networks:
      - web-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s

  web:
    <<: &web
      image: "employeebook:dev"
      volumes:
        - django-static:/var/www/django/static
      networks:
        - web-net
        - postgres-net
      env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: python -We -bb backend/manage.py runserver 0.0.0.0:8000

  celery_worker:
    <<: *web
    environment:
        PYTHONPATH: /code/backend
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: python -m celery -A employeebook.celery:app worker --loglevel=info

  celery_beat:
    <<: *web
    environment:
        PYTHONPATH: /code/backend
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: >
        python -m celery -A employeebook.celery:app beat
        --loglevel=info
        --scheduler django_celery_beat.schedulers:DatabaseScheduler

networks:
  postgres-net:
  web-net:

volumes:
  postgres-data:
  django-static:
