# Generated by Django 6.0.4 on 2026-05-12 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                (
                    'name',
                    models.CharField(
                        help_text='Уникально в рамках родительского подразделения',
                        max_length=255,
                        verbose_name='Название',
                    ),
                ),
                (
                    'short_name',
                    models.CharField(blank=True, max_length=50, null=True, verbose_name='Сокращенное название'),
                ),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                (
                    'type',
                    models.CharField(
                        choices=[('direction', 'Направление'), ('department', 'Отдел')],
                        default='department',
                        max_length=20,
                        verbose_name='Тип',
                    ),
                ),
                ('display_order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                (
                    'deleted_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='deleted_departments',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Кем удалено',
                    ),
                ),
                (
                    'parent',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='children',
                        to='structure.department',
                        verbose_name='Родительское подразделение',
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='updated_departments',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Кем обновлено',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
                'ordering': ('display_order', 'name'),
                'constraints': [models.UniqueConstraint(fields=('parent', 'name'), name='unique_name_per_parent')],
            },
        ),
    ]
