# Generated by Django 6.0.4 on 2026-06-20 22:47

import core.storage
import medias.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgStructureImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=core.storage.HashedFileStorage(), upload_to='org-structure/', validators=[medias.validators.validate_org_image_extension, medias.validators.validate_file_size], verbose_name='Изображение')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Изображение оргструктуры',
                'verbose_name_plural': 'Изображение оргструктуры',
            },
        ),
    ]
