# Generated by Django 6.0.4 on 2026-07-04 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('employees', '0004_add_employee_fields'),
        ('structure', '0002_orgstructureimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='headed_departments',
                to='employees.employee',
                verbose_name='Руководитель',
            ),
        ),
    ]
