# Generated by Django 6.0.4 on 2026-05-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'name',
                    models.CharField(
                        help_text='Название тега должно быть уникальным.',
                        max_length=100,
                        unique=True,
                        verbose_name='Название тега',
                    ),
                ),
                (
                    'color_or_icon',
                    models.CharField(
                        blank=True,
                        help_text='Цветовое обозначение (например, #FF0000)или идентификатор значка.',
                        max_length=50,
                        verbose_name='Цвет или иконка',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['name'],
            },
        ),
    ]
