# Generated by Django 6.0.4 on 2026-05-18 09:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('employees', '0001_initial'),
        ('tags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'assigned_at',
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text='Дата и время присвоения тега.',
                        verbose_name='Когда назначен тег',
                    ),
                ),
                (
                    'assigned_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='assigned_employee_tags',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Кем назначен тег',
                    ),
                ),
                (
                    'employee',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='employee_tags',
                        to='employees.employee',
                        verbose_name='Сотрудник',
                    ),
                ),
                (
                    'tag',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='employee_tags',
                        to='tags.tag',
                        verbose_name='Тег',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Тег сотрудника',
                'verbose_name_plural': 'Теги сотрудника',
                'ordering': ['-assigned_at'],
                'constraints': [models.UniqueConstraint(fields=('tag', 'employee'), name='unique_tag_employee')],
            },
        ),
    ]
