# Generated by Django 6.0.4 on 2026-05-31 14:48

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tags', '0002_employeetag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='employeetag',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='employeetag',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeetag',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='employeetag',
            name='removed_at',
            field=models.DateTimeField(
                blank=True, help_text='Дата и время удаления тега.', null=True, verbose_name='Когда удален тег'
            ),
        ),
        migrations.AddField(
            model_name='employeetag',
            name='removed_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='removed_employee_tags',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Кем удален тег',
            ),
        ),
        migrations.AlterField(
            model_name='employeetag',
            name='assigned_by',
            field=models.ForeignKey(
                blank=True,
                db_column='assigned_by_id',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='assigned_employee_tags',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Кем назначен тег',
            ),
        ),
    ]
