# Generated by Django 6.0.4 on 2026-05-25 18:05

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('tags', '0002_employeetag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='employeetag',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='employeetag',
            old_name='assigned_by',
            new_name='assigned_by_id',
        ),
        migrations.AddField(
            model_name='employeetag',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeetag',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='employeetag',
            name='removed_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Дата и время удаления тега.', verbose_name='Когда удален тег'),
        ),
        migrations.AddField(
            model_name='employeetag',
            name='removed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='removed_employee_tags', to=settings.AUTH_USER_MODEL, verbose_name='Кем удален тег'),
        ),
        migrations.AlterField(
            model_name='employeetag',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_tags', to='employees.employee', verbose_name='Сотрудник'),
        ),
    ]
