# Generated by Django 6.0.4 on 2026-05-29 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_alter_employeetag_managers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeetag',
            name='assigned_by_id',
        ),
        migrations.AddField(
            model_name='employeetag',
            name='assigned_by',
            field=models.ForeignKey(blank=True, db_column='assigned_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_employee_tags', to=settings.AUTH_USER_MODEL, verbose_name='Кем назначен тег'),
        ),
        migrations.AlterField(
            model_name='employeetag',
            name='removed_at',
            field=models.DateTimeField(blank=True, help_text='Дата и время удаления тега.', null=True, verbose_name='Когда удален тег'),
        ),
    ]
