# Generated by Django 6.0.4 on 2026-06-11 10:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('tags', '0003_add_removed_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='color_or_icon',
        ),
    ]
