# Generated by Django 6.0.4 on 2026-06-15 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                (
                    'status',
                    models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10),
                ),
                (
                    'department',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name='vacancies', to='structure.department'
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
