# Generated by Django 6.0.4 on 2026-05-18 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structure', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=255, verbose_name='Полное имя')),
                ('job_title', models.CharField(max_length=255, verbose_name='Должность')),
                ('role_description', models.TextField(blank=True, verbose_name='Роль')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Электронная почта')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('interests', models.TextField(blank=True, verbose_name='Компетенции')),
                ('birthday', models.DateField(verbose_name='День рождения')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('archived', 'Архивированный')], default='active', max_length=20, verbose_name='Статус')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_employees', to=settings.AUTH_USER_MODEL, verbose_name='Кем создано')),
                ('department', models.ForeignKey(limit_choices_to={'type': 'department'}, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='structure.department', verbose_name='Отдел')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_employees', to=settings.AUTH_USER_MODEL, verbose_name='Кем обновлено')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ('full_name',),
            },
        ),
    ]
