# Generated by Django 6.0.4 on 2026-05-29 09:05

import medias.validators
from django.db import migrations, models

import core.storage


class Migration(migrations.Migration):
    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(
                blank=True,
                null=True,
                storage=core.storage.HashedFileStorage(),
                upload_to='photos/originals/',
                validators=[medias.validators.validate_file_extension, medias.validators.validate_file_size],
                verbose_name='Оригинальное фото',
            ),
        ),
        migrations.AddField(
            model_name='employee',
            name='photo_thumb',
            field=models.ImageField(
                blank=True,
                editable=False,
                null=True,
                storage=core.storage.HashedFileStorage(),
                upload_to='photos/thumbs/',
                verbose_name='Миниатюра',
            ),
        ),
    ]
