# Generated by Django 6.0.4 on 2026-06-18 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_inaccuracyreport'),
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='employee',
            name='crm_profile',
            field=models.URLField(blank=True, null=True, verbose_name='Профиль в CRM'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employment_status',
            field=models.CharField(choices=[('working', 'Работает'), ('vacation', 'В отпуске'), ('sick_leave', 'На больничном'), ('maternity_leave', 'В декрете'), ('business_trip', 'В командировке'), ('remote', 'На удалёнке')], default='working', max_length=50, verbose_name='Статус работы'),
        ),
        migrations.AddField(
            model_name='employee',
            name='personal_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Личная почта'),
        ),
        migrations.AddField(
            model_name='employee',
            name='personal_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Личный телефон'),
        ),
        migrations.AddField(
            model_name='employee',
            name='resume_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на резюме'),
        ),
        migrations.AddField(
            model_name='employee',
            name='social_network',
            field=models.URLField(blank=True, null=True, verbose_name='Социальная сеть'),
        ),
        migrations.AddField(
            model_name='employee',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='employees.employee', verbose_name='Руководитель'),
        ),
        migrations.AddField(
            model_name='employee',
            name='supervisor_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor_photos', to='employees.employee', verbose_name='Фото руководителя'),
        ),
        migrations.AddField(
            model_name='employee',
            name='supervisor_role',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'department'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor_roles', to='structure.department', verbose_name='Должность руководителя'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role_description',
            field=models.JSONField(blank=True, default=list, help_text='Список ролей или обязанностей сотрудника', verbose_name='Роль'),
        ),
    ]
